--liquibase formatted sql

-- Copyright (c) 2022. stockapp.
-- Proprietary source code; any copy or modification is prohibited.
--
-- @author Moulaye Abderrahmane <moolsbytheway@gmail.com>
--

--changeset init:1
CREATE SEQUENCE hibernate_sequence
    START WITH 100;


create table bill
(
    ID          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider    bigint,
    ref         varchar(255),
    paid_date   timestamp,
    BILL_AMOUNT real,
    created_at  timestamp,
    paid_by_id  bigint,
    primary key (id)
);

create table app_user
(
    ID          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    active_user boolean default false,
    busy        boolean default false,
    created_at  timestamp,
    email       varchar(255),
    role        bigint,
    phone       varchar(24),
    first_name  varchar(255),
    birth_date  timestamp,
    language    varchar(255),
    last_name   varchar(255),
    password    varchar(255),
    reset_token varchar(255),
    username    varchar(255),
    primary key (id)
);



ALTER TABLE app_user
    ADD CONSTRAINT UNIQUE_username UNIQUE (username);



ALTER TABLE app_user
    ADD CONSTRAINT UNIQUE_phone UNIQUE (phone);



alter table bill
    add constraint fk_bill_paid_by_user
        foreign key (paid_by_id)
            references app_user;